//! Database schema definitions
//! 
//! This file will be auto-generated by Diesel CLI during Phase 1
//! For now, we provide placeholder schemas

use diesel::table;

table! {
    tenants (id) {
        id -> Int8,
        external_id -> Uuid,
        name -> Varchar,
        identifier -> Varchar,
        schema_name -> Varchar,
        timezone -> Varchar,
        country_code -> Varchar,
        created_at -> Timestamptz,
        updated_at -> Nullable<Timestamptz>,
        is_active -> Bool,
    }
}

table! {
    users (id) {
        id -> Int8,
        external_id -> Uuid,
        username -> Varchar,
        email -> Varchar,
        password_hash -> Varchar,
        first_name -> Varchar,
        last_name -> Varchar,
        status -> Varchar,
        created_at -> Timestamptz,
        updated_at -> Nullable<Timestamptz>,
        last_login -> Nullable<Timestamptz>,
        is_system_user -> Bool,
    }
}