// @generated automatically by Diesel CLI.

diesel::table! {
    m_appuser (id) {
        id -> Int8,
        username -> Varchar,
        email -> Varchar,
        firstname -> Varchar,
        lastname -> Varchar,
        password -> Varchar,
        nonexpired -> Bool,
        nonlocked -> Bool,
        nonexpired_credentials -> Bool,
        enabled -> Bool,
        last_time_password_updated -> Timestamp,
        password_never_expires -> Bool,
        is_deleted -> Bool,
        created_date -> Timestamp,
        lastmodified_date -> Timestamp,
        createdby_id -> Int8,
        lastmodifiedby_id -> Int8,
    }
}

diesel::table! {
    m_client (id) {
        id -> Int8,
        account_no -> Varchar,
        external_id -> Varchar,
        status_enum -> Int2,
        sub_status -> Int2,
        activation_date -> Date,
        office_id -> Int8,
        transfer_to_office_id -> Int8,
        staff_id -> Int8,
        firstname -> Varchar,
        middlename -> Varchar,
        lastname -> Varchar,
        fullname -> Varchar,
        display_name -> Varchar,
        mobile_no -> Varchar,
        date_of_birth -> Date,
        gender_cv_id -> Int4,
        client_type_cv_id -> Int4,
        client_classification_cv_id -> Int4,
        is_staff -> Bool,
        is_deleted -> Bool,
        created_date -> Timestamp,
        lastmodified_date -> Timestamp,
        createdby_id -> Int8,
        lastmodifiedby_id -> Int8,
    }
}

diesel::table! {
    m_loan (id) {
        id -> Int8,
        account_no -> Varchar,
        external_id -> Varchar,
        client_id -> Int8,
        group_id -> Int8,
        product_id -> Int8,
        fund_id -> Int8,
        loan_officer_id -> Int8,
        loan_status_id -> Int2,
        loan_type_enum -> Int2,
        currency_code -> Varchar,
        currency_digits -> Int2,
        currency_multiplesof -> Int2,
        principal_amount_proposed -> Numeric,
        principal_amount -> Numeric,
        approved_principal_amount -> Numeric,
        net_disbursal_amount -> Numeric,
        total_expected_repayment_derived -> Numeric,
        total_repayment_derived -> Numeric,
        total_outstanding_derived -> Numeric,
        total_overpaid_derived -> Numeric,
        total_writtenoff_derived -> Numeric,
        total_charges_charged_derived -> Numeric,
        total_charges_paid_derived -> Numeric,
        total_penalties_charged_derived -> Numeric,
        total_penalties_paid_derived -> Numeric,
        total_interest_charged_derived -> Numeric,
        total_interest_paid_derived -> Numeric,
        total_fee_charges_charged_derived -> Numeric,
        total_fee_charges_paid_derived -> Numeric,
        submittedon_date -> Date,
        submittedon_userid -> Int8,
        approvedon_date -> Date,
        approvedon_userid -> Int8,
        expected_disbursedon_date -> Date,
        expected_disbursedon_userid -> Int8,
        actual_disbursedon_date -> Date,
        actual_disbursedon_userid -> Int8,
        closedon_date -> Date,
        closedon_userid -> Int8,
        expected_maturedon_date -> Date,
        matured_on_date -> Date,
        matured_on_userid -> Int8,
        written_off_on_date -> Date,
        written_off_on_userid -> Int8,
        rescheduled_on_date -> Date,
        rescheduled_on_userid -> Int8,
        rescheduled_outstanding_loan_installment_number -> Int4,
        sync_disbursement_with_meeting -> Bool,
        loan_counter -> Int4,
        loan_product_counter -> Int4,
        is_npa -> Bool,
        days_in_year_enum -> Int2,
        days_in_month_enum -> Int2,
        interest_recalculation_enabled -> Bool,
        create_standing_instruction_at_disbursement -> Bool,
        is_deleted -> Bool,
        created_date -> Timestamp,
        lastmodified_date -> Timestamp,
        createdby_id -> Int8,
        lastmodifiedby_id -> Int8,
    }
}

diesel::table! {
    m_savings_account (id) {
        id -> Int8,
        account_no -> Varchar,
        external_id -> Varchar,
        client_id -> Int8,
        group_id -> Int8,
        product_id -> Int8,
        field_officer_id -> Int8,
        status_enum -> Int2,
        sub_status_enum -> Int2,
        currency_code -> Varchar,
        currency_digits -> Int2,
        currency_multiplesof -> Int2,
        nominal_annual_interest_rate -> Numeric,
        interest_compounding_period_enum -> Int2,
        interest_posting_period_enum -> Int2,
        interest_calculation_type_enum -> Int2,
        interest_calculation_days_in_year_type_enum -> Int2,
        min_required_opening_balance -> Numeric,
        lockin_period_frequency -> Int4,
        lockin_period_frequency_enum -> Int2,
        withdrawal_fee_for_transfer -> Bool,
        allow_overdraft -> Bool,
        overdraft_limit -> Numeric,
        min_required_balance -> Numeric,
        enforce_min_required_balance -> Bool,
        min_balance_for_interest_calculation -> Numeric,
        on_hold_fund_derived -> Numeric,
        total_deposits_derived -> Numeric,
        total_withdrawals_derived -> Numeric,
        total_withdrawal_fees_derived -> Numeric,
        total_fees_charge_derived -> Numeric,
        total_fees_paid_derived -> Numeric,
        total_penalties_charge_derived -> Numeric,
        total_penalties_paid_derived -> Numeric,
        total_annual_fees_derived -> Numeric,
        total_interest_earned_derived -> Numeric,
        total_interest_posted_derived -> Numeric,
        account_balance_derived -> Numeric,
        total_fee_charges_waived_derived -> Numeric,
        total_penalties_waived_derived -> Numeric,
        total_annual_fees_waived_derived -> Numeric,
        total_interest_waived_derived -> Numeric,
        on_hold_fund_derived_until -> Date,
        is_deleted -> Bool,
        created_date -> Timestamp,
        lastmodified_date -> Timestamp,
        createdby_id -> Int8,
        lastmodifiedby_id -> Int8,
    }
}

diesel::allow_tables_to_appear_in_same_query!(
    m_appuser,
    m_client,
    m_loan,
    m_savings_account,
);